### ISSUE TITLE
Are there any plans adding Linux support?

### ISSUE THREAD

**Issue by NuLL3rr0r** [Conv-AI/Convai-UnrealEngine-SDK#20]
Unfortunately, my project is a Linux project since it's a live stream running by AI. I cannot run on Windows. Are there any plans to add support for Linux?

**Comment by MohamedEshmawy** [comment]
Hi @NuLL3rr0r, yes indeed we should have initial support for Linux by next week.

**Comment by NuLL3rr0r** [comment]
Thank you! Will check it out.
