### ISSUE TITLE
in unreal engine source build cant build Dedicated server  

### ISSUE THREAD

**Issue by zakaria2006** [Conv-AI/Convai-UnrealEngine-SDK#7]
i try build with Dedicated  server i get this error : 

1>Missing precompiled manifest for 'Convai', 'C:\UE5\tempProject\VSG3\Intermediate\Build\Win64\VSG3Server\Development\Convai\Convai.precompiled'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in Convai.build.cs to override. If part of a plugin, also check if its 'Type' is correct.

Version 5.2

**Comment by MohamedEshmawy** [comment]
Hello, to build for windows you will have to comment out a line in convai.build.cs file. comment out the bUsePrecompiled = true line.
